name: Docker website CI
on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    env:
      TF_VAR_resource_group_name: "rg-ms-cqrs"
      TF_VAR_location:           "eastus2"

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build website image
      run: | 
        docker build --platform linux --tag aminespinoza/coffeeshop:latest -f src/Dockerfile .
    - name: Publish website image
      run: |
        docker push aminespinoza/coffeeshop:latest
    - name: App service auth
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aminescoffeshop'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'aminespinoza/coffeeshop:latest'