name: Docker Image CI

# on:
#   push:
#     branches: [ "dev" ]
#   pull_request:
#     branches: [ "dev" ]
on:
  workflow_dispatch:
      inputs:
        reason:
          description: 'Razón del despliegue manual'
          required: false
          default: 'Mantenimiento manual'
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build website image
      run: | 
        docker build --platform linux --tag juniorllancari/cqrswebapi:${{ github.sha }} -f src/CQRS.Api/Dockerfile .
    - name: Publish website image
      run: |
        docker push juniorllancari/cqrswebapi:${{ github.sha }}

  deploy:
      name: Container App Deploy
      needs: build
      runs-on: ubuntu-latest
      env:
        TF_VAR_resource_group_name: "rg-ms-cqrs"
        TF_VAR_location:           "eastus2"



      steps:
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Install Container App Extension
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az extension add --name containerapp --upgrade

      - name: Update Container App
        run: |
          az containerapp update \
            --name "juniorllancariapp" \
            --resource-group "rg-ms-cqrs" \
            --image docker.io/juniorllancari/cqrswebapi:${{ github.sha }}